/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/ui/accordion/Accordion.vue')['default']
    AccordionContent: typeof import('./src/components/ui/accordion/AccordionContent.vue')['default']
    AccordionItem: typeof import('./src/components/ui/accordion/AccordionItem.vue')['default']
    AccordionTrigger: typeof import('./src/components/ui/accordion/AccordionTrigger.vue')['default']
    Achievement: typeof import('./src/components/shared/Achievement.vue')['default']
    Avatar: typeof import('./src/components/ui/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./src/components/ui/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./src/components/ui/avatar/AvatarImage.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    ButtonIcon: typeof import('./src/components/shared/ButtonIcon.vue')['default']
    ButtonLink: typeof import('./src/components/shared/ButtonLink.vue')['default']
    ButtonModeColor: typeof import('./src/components/shared/ButtonModeColor.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardAction: typeof import('./src/components/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardInfo: typeof import('./src/components/shared/CardInfo.vue')['default']
    CardProgress: typeof import('./src/components/shared/CardProgress.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Login: typeof import('./src/components/auth/login.vue')['default']
    MyService: typeof import('./src/components/shared/MyService.vue')['default']
    NarbraAdmin: typeof import('./src/components/NarbraAdmin.vue')['default']
    Navbar: typeof import('./src/components/shared/Navbar.vue')['default']
    PersonalInfo: typeof import('./src/components/shared/PersonalInfo.vue')['default']
    Porfile: typeof import('./src/components/shared/Porfile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./src/components/shared/ServiceCard.vue')['default']
    SideBarLeft: typeof import('./src/components/shared/SideBarLeft.vue')['default']
    SideBarRight: typeof import('./src/components/shared/SideBarRight.vue')['default']
    Skeleton: typeof import('./src/components/ui/skeleton/Skeleton.vue')['default']
    Tooltip: typeof import('./src/components/ui/tooltip/Tooltip.vue')['default']
    TooltipButton: typeof import('./src/components/shared/TooltipButton.vue')['default']
    TooltipContent: typeof import('./src/components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./src/components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./src/components/ui/tooltip/TooltipTrigger.vue')['default']
    WorkExperience: typeof import('./src/components/shared/work-experience.vue')['default']
  }
}
